// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/**
 * Prisma CLI (migrate / db push / studio) connection.
 *
 * Prefer DIRECT_URL when set — required for Supabase so migrations use the
 * direct Postgres port (5432) instead of the transaction pooler (6543).
 * Falls back to DATABASE_URL for local Docker (single URL is fine).
 *
 * For build-time only (when no real database is available), uses a dummy URL
 * just for schema validation and client generation.
 *
 * Runtime PrismaClient still uses DATABASE_URL via the pg adapter in lib/db.ts.
 */

// Use dummy database URL for build environments without database access
const getDatabaseUrl = () => {
  const directUrl = process.env['DIRECT_URL'];
  const databaseUrl = process.env['DATABASE_URL'];
  
  // If we have a real database URL, use it
  if (directUrl && directUrl !== '') return directUrl;
  if (databaseUrl && databaseUrl !== '' && !databaseUrl.includes('dummy')) return databaseUrl;
  
  // Fallback for build environments - dummy URL for schema validation only
  return 'postgresql://dummy:dummy@localhost:5432/dummy';
};

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
