import {
  BookOpen,
  CircleUser,
  CreditCard,
  FolderTree,
  GraduationCap,
  Heart,
  Inbox,
  LayoutDashboard,
  type LucideIcon,
  Map,
  Megaphone,
  Radio,
  ScrollText,
  Settings,
  Star,
  UserCog,
  Users,
} from 'lucide-react';

/** Serializable icon keys → lucide icons (keeps the RSC prop boundary clean). */
export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  courses: BookOpen,
  live: Radio,
  wishlist: Heart,
  categories: FolderTree,
  reviews: Star,
  inquiries: Inbox,
  enrollments: GraduationCap,
  paths: Megaphone,
  payments: CreditCard,
  batches: Users,
  plans: Map,
  instructors: UserCog,
  students: Users,
  profile: CircleUser,
  settings: Settings,
  audit: ScrollText,
};
